third_party_settings:
  shortcut:
    module_link: true
features:
  node_user_picture: false
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
